const {test} = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
function setup(values = {}, fetch = () => {throw Error('unexpected');}) {
  const props = {...values}, calls = [], emails = [], triggers = [];
  const ctx = {Date, JSON, console: {log() {}},
    PropertiesService: {getScriptProperties: () => ({getProperty: k => props[k], setProperty: (k,v) => {props[k]=v;}, deleteProperty: k => {delete props[k];}})},
    LockService: {getScriptLock: () => ({tryLock: () => true, releaseLock() {}})},
    Utilities: {getUuid: () => '11111111-1111-1111-1111-111111111111'},
    UrlFetchApp: {fetch: (url, options) => {calls.push({url, options}); return fetch(url, options);}},
    MailApp: {sendEmail: (...a) => emails.push(a)},
    ScriptApp: {getProjectTriggers: () => triggers, newTrigger: name => ({timeBased: () => ({everyMinutes: () => ({create: () => triggers.push({getHandlerFunction: () => name})})})}), deleteTrigger: t => triggers.splice(triggers.indexOf(t),1)}};
  vm.createContext(ctx);vm.runInContext(fs.readFileSync('gas/ActionsClock.js','utf8'),ctx);
  return {ctx, props, calls, emails, triggers};
}
const response = (code, data={}) => ({getResponseCode:()=>code,getContentText:()=>JSON.stringify(data)});
test('停止既定では認証も通信も不要',()=>{const x=setup();assert.equal(x.ctx.tickActionsClock().state,'disabled');assert.equal(x.calls.length,0);assert.throws(()=>x.ctx.installActionsClock(),/MIGRATION/);});
test('DM単発は試験ブランチだけ・定期トリガーなし・再実行拒否',()=>{const x=setup({ACTIONS_CLOCK_TOKEN:'dummy'},()=>response(204));x.ctx.runActionsClockOwnerSmoke();const p=JSON.parse(x.calls[0].options.payload);assert.equal(p.ref,'slack-http');assert.equal(p.inputs.owner_dm_smoke,true);assert.equal(p.inputs.clock_request_id,x.ctx.healthActionsClock().smoke.requestId);assert.equal(x.triggers.length,0);assert.throws(()=>x.ctx.runActionsClockOwnerSmoke(),/ALREADY/);});
test('POST結果不明でも再送せず秘密値を出さない',()=>{const x=setup({ACTIONS_CLOCK_TOKEN:'dummy'},()=>{throw Error('secret');});assert.throws(()=>x.ctx.runActionsClockOwnerSmoke(),/CLOCK_TRANSPORT_UNKNOWN/);assert.throws(()=>x.ctx.runActionsClockOwnerSmoke(),/ALREADY/);assert.equal(x.calls.length,1);assert.equal(JSON.parse(x.props.ACTIONS_CLOCK_SMOKE_REQUEST).state,'unknown');});
test('401/403/429/500を成功扱いしない',()=>{for(const code of [401,403,429,500]){const x=setup({ACTIONS_CLOCK_TOKEN:'dummy'},()=>response(code));assert.throws(()=>x.ctx.runActionsClockOwnerSmoke(),new RegExp('CLOCK_GITHUB_'+code));}});
const enabled = {ACTIONS_CLOCK_ENABLED:'true',ACTIONS_CLOCK_MIGRATION_ACK:'true',ACTIONS_CLOCK_TOKEN:'dummy',HEALTH_EMAIL:'owner@example.test'};
function api(url, options){if(options.method==='post')return response(204);if(url.includes('status='))return response(200,{total_count:url.includes('bot.yml')&&url.includes('in_progress')?1:0,workflow_runs:url.includes('bot.yml')&&url.includes('in_progress')?[{head_branch:'main',status:'in_progress'}]:[]});return response(200,{workflow_runs:[{status:'completed',conclusion:'success',updated_at:new Date().toISOString()}]});}
test('稼働中Botを起動せず認証更新だけ要求',()=>{const x=setup(enabled,api);assert.equal(x.ctx.tickActionsClock().ok,true);const posts=x.calls.filter(c=>c.options.method==='post');assert.equal(posts.length,1);assert.match(posts[0].url,/auth-refresh.yml\/dispatches$/);});
test('未照合の要求は次周期で再送しない',()=>{const x=setup(enabled,api);x.ctx.tickActionsClock();x.ctx.tickActionsClock();assert.equal(x.calls.filter(c=>c.options.method==='post').length,1);});
test('稼働中の認証更新があれば送らない',()=>{const x=setup(enabled,(u,o)=>u.includes('auth-refresh.yml')&&u.includes('status=in_progress')?response(200,{total_count:1,workflow_runs:[{}]}):api(u,o));x.ctx.tickActionsClock();assert.equal(x.calls.filter(c=>c.options.method==='post').length,0);});
test('無効化は時計だけを削除',()=>{const x=setup(enabled);x.ctx.installActionsClock();x.ctx.installActionsClock();assert.equal(x.triggers.length,1);x.triggers.push({getHandlerFunction:()=> 'pollSalesQa'});x.ctx.stopActionsClock();assert.equal(x.props.ACTIONS_CLOCK_ENABLED,'false');assert.equal(x.triggers.length,1);assert.equal(x.triggers[0].getHandlerFunction(),'pollSalesQa');});
test('移行ACKなしでは通信せず通知',()=>{const x=setup({...enabled,ACTIONS_CLOCK_MIGRATION_ACK:'false'});assert.equal(x.ctx.tickActionsClock().ok,false);assert.equal(x.calls.length,0);assert.equal(x.emails.length,1);});
test('実行一覧が不完全なら送らない',()=>{const x=setup(enabled,()=>response(200,{total_count:101,workflow_runs:[]}));assert.equal(x.ctx.tickActionsClock().ok,false);assert.equal(x.calls.filter(c=>c.options.method==='post').length,0);});

test('待機中Botは稼働確認にならない',()=>{const x=setup(enabled,(u,o)=>u.includes('bot.yml')?response(200,{total_count:1,workflow_runs:[{head_branch:'main',status:'queued'}]}):api(u,o));assert.equal(x.ctx.tickActionsClock().ok,false);});
test('保留要求の識別子と異常理由を確認できる',()=>{const pending={requestId:'test',requestedAt:'2020-01-01T00:00:00Z'};const x=setup({...enabled,ACTIONS_CLOCK_AUTH_REQUEST:JSON.stringify(pending)},api);assert.equal(x.ctx.tickActionsClock().code,'CLOCK_REQUEST_UNCONFIRMED');assert.equal(x.ctx.healthActionsClock().pendingAuthRequest.requestId,'test');});
test('確定拒否は結果不明と区別する',()=>{const x=setup({ACTIONS_CLOCK_TOKEN:'dummy'},()=>response(422));assert.throws(()=>x.ctx.runActionsClockOwnerSmoke(),/422/);assert.equal(JSON.parse(x.props.ACTIONS_CLOCK_SMOKE_REQUEST).state,'rejected');assert.throws(()=>x.ctx.runActionsClockOwnerSmoke(),/ALREADY/);});
test('一時的に状態が揺れても通知を連発しない',()=>{const x=setup(enabled);x.ctx.actionsClockNotice_({ok:true});x.ctx.actionsClockNotice_({ok:false,code:'CLOCK_BOT_NOT_RUNNING'});x.ctx.actionsClockNotice_({ok:true});assert.equal(x.emails.length,1);});
test('一致した要求だけを解除して次の更新へ進む',()=>{const pending={requestId:'test',requestedAt:new Date().toISOString()};const x=setup({...enabled,ACTIONS_CLOCK_AUTH_REQUEST:JSON.stringify(pending)},(u,o)=>u.includes('branch=main')&&!u.includes('status=')?response(200,{workflow_runs:[{display_title:'GAS認証更新 test',status:'completed',conclusion:'success',updated_at:new Date().toISOString()}]}):api(u,o));x.ctx.tickActionsClock();assert.equal(x.calls.filter(c=>c.options.method==='post').length,1);assert.notEqual(JSON.parse(x.props.ACTIONS_CLOCK_AUTH_REQUEST).requestId,'test');});

test('Botの未完了がなければ停止確認workflowだけを要求',()=>{const x=setup(enabled,(u,o)=>u.includes('bot.yml')?response(200,{total_count:0,workflow_runs:[]}):api(u,o));x.ctx.tickActionsClock();const posts=x.calls.filter(c=>c.options.method==='post');assert.equal(posts.length,2);assert.match(posts[1].url,/bot-watchdog.yml\/dispatches$/);assert.equal(JSON.parse(posts[1].options.payload).ref,'main');assert.equal(x.ctx.healthActionsClock().pendingRecoveryRequest.state,'accepted');x.ctx.tickActionsClock();assert.equal(x.calls.filter(c=>c.options.method==='post').length,2);});
test('待機中Botがあれば復旧要求しない',()=>{const x=setup(enabled,(u,o)=>u.includes('bot.yml')?response(200,{total_count:1,workflow_runs:[{head_branch:'main',status:'pending'}]}):api(u,o));x.ctx.tickActionsClock();assert.equal(x.calls.filter(c=>c.options.method==='post'&&c.url.includes('bot-watchdog')).length,0);});
test('件数不一致・件数不明を停止とみなさない',()=>{for(const d of [{workflow_runs:[]},{total_count:1,workflow_runs:[]},{total_count:-1,workflow_runs:[]}]){const x=setup(enabled,(u,o)=>u.includes('bot.yml')?response(200,d):api(u,o));assert.equal(x.ctx.tickActionsClock().code,'CLOCK_RUN_LIST_UNCERTAIN');assert.equal(x.calls.filter(c=>c.options.method==='post'&&c.url.includes('bot-watchdog')).length,0);}});
test('復旧POSTの応答消失時も次周期で再送しない',()=>{const x=setup(enabled,(u,o)=>u.includes('bot-watchdog')&&o.method==='post'?(()=>{throw Error('応答不明');})():u.includes('bot.yml')?response(200,{total_count:0,workflow_runs:[]}):api(u,o));x.ctx.tickActionsClock();x.ctx.tickActionsClock();assert.equal(x.calls.filter(c=>c.options.method==='post'&&c.url.includes('bot-watchdog')).length,1);assert.equal(x.ctx.healthActionsClock().pendingRecoveryRequest.state,'unknown');});

test('停止確認が未完了なら追加復旧要求しない',()=>{const x=setup(enabled,(u,o)=>u.includes('bot-watchdog')&&u.includes('status=in_progress')?response(200,{total_count:1,workflow_runs:[{head_branch:'main',status:'in_progress'}]}):u.includes('bot.yml')?response(200,{total_count:0,workflow_runs:[]}):api(u,o));x.ctx.tickActionsClock();assert.equal(x.calls.filter(c=>c.options.method==='post'&&c.url.includes('bot-watchdog')).length,0);});
test('古い復旧要求は未照合の日本語通知を出す',()=>{const x=setup({...enabled,ACTIONS_CLOCK_RECOVERY_REQUEST:JSON.stringify({requestId:'old',requestedAt:'2020-01-01T00:00:00Z'})},api);assert.equal(x.ctx.tickActionsClock().code,'CLOCK_RECOVERY_UNCONFIRMED');assert.match(x.emails[0][2],/停止確認の起動要求を10分以上照合/);});
test('復旧要求は一致する実行名を確認して解除する',()=>{const x=setup({...enabled,ACTIONS_CLOCK_RECOVERY_REQUEST:JSON.stringify({requestId:'found',requestedAt:new Date().toISOString()})},(u,o)=>u.includes('bot-watchdog')&&!u.includes('status=')?response(200,{workflow_runs:[{display_title:'GAS停止確認 found'}]}):api(u,o));x.ctx.tickActionsClock();assert.equal(x.ctx.healthActionsClock().pendingRecoveryRequest,null);assert.equal(x.calls.filter(c=>c.options.method==='post'&&c.url.includes('bot-watchdog')).length,0);});
